### ISSUE TITLE
Define interaction with setMediaKeys() / Encrypted Media Extensions

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#55]
Some user agents may or may not be able to remote video with media keys set before or during remoting.   The spec should provide some guidance as to what developers should expect when `setMediaKeys()` [1] is called on a remotable media element.

[1] https://w3c.github.io/encrypted-media/#htmlmediaelement-extensions

**Comment by avayvod** [comment]
The strawman proposal from #41 was to do the following:

`readonly attribute MediaKeys mediaKeys;`

MAY support. Return `null` otherwise.

`Promise setMediaKeys(MediaKeys? mediaKeys);`

MAY support. Reject with `NotSupportedError`.

`attribute EventHandler onencrypted;`

MAY support. Otherwise, no-op.

`attribute EventHandler onwaitingforkey;`

MAY support. Otherwise, no-op.

It doesn't describe how it should work if it is supported.

**Comment by mounirlamouri** [comment]
Merging with #41.
