### ISSUE TITLE
prompt() should not be rejected if the state was connected when called

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/remote-playback#63]
IMO, "6.2.2 Prompt user for changing remote playback state" should be changed to include a step between current 11 and 12 so that if the state was `connected` and remained `connected`. Such that the user did not change the connecting device, the promise should be fulfilled. At the moment, it would be rejected which could be very surprising when the user is in a connected state because the UA could include options in this dialog such as changing volume stream, etc. Rejecting the promise would mostly create noise for the website.

**Comment by avayvod** [comment]
It is similar to `PresentationRequest.start()` which always rejects if the dialog is dismissed. Otherwise if the `state` is `connected`, promise returned by `prompt()` is useless.

``` javascript
btn.onclick = function() {
  if (v.remote.state === 'disconnected') {
    v.remote.prompt().then(switchToRemoteState, showError);
  } else {
    v.remote.prompt().then(switchToLocalState);
  }
};
```

The latter would be impossible if we always resolve the promise when `connected`.

If we really want to simplify it, we could just abandon the promise altogether and rely on the events - the website has to handle the events anyway because the connection can be initiated by the browser or dropped due to Wi-Fi - both without `prompt()` being called at all.

**Comment by mounirlamouri** [comment]
WebKit work in progress patch seems to also implement it the way the spec says. I guess if both you and @jernoble had no concern, let's close this.
