### ISSUE TITLE
Should the ability to query by language or country be added to watchAvailability()

### ISSUE THREAD

**Issue by stevenatkin** [w3c/remote-playback#70]
6.2.1.3 Getting the remote playback devices availability information
https://w3c.github.io/remote-playback/#getting-the-remote-playback-devices-availability-information

Would there be a need to query remote device playback availability based upon language and our country? Could we have a situation where there would be some specific hardware that would need to be selected based upon language? For example, could there be a case where the remote playback device had a specialized set of script specific fonts that were going to be used to display captions.

**Comment by markafoltz** [comment]
This could be tricky because for a given media element:
- There can be multiple languages conveyed by different WebVTT `<tracks>`/cue sheets.
- The browser may not know what languages are conveyed by text tracks inside the media resource until playback begins.
- We don't know what language the user will choose for captions, and can change it during playback.

Given the uncertainty I'm not sure the browser should hide a playback device based on lack of a specific font - we can't predict whether that will be relevant to playback or not.

@avayvod @mounirlamouri Any thoughts?

**Comment by avayvod** [comment]
I don't think Cast devices support such filtering mechanism, for example.

In Presentation API case, the page can send a message to the receiver to figure out what language is needed. Perhaps, Remote Playback API could have a way to express a language preference, like pass the locale info as a parameter to the watchAvailability() call, but I'd err on the side of let's add it when there's demand.

**Comment by avayvod** [comment]
On the other hand, ```TextTrack``` has ```srclang``` property that could be used as a hint to the UA.

**Comment by steveatkin** [comment]
If you can use the srcLang to indicate the language as a hint that would be ok.

**Comment by anssiko** [comment]
@steveatkin @mounirlamouri, see #99 for a suggested informative text to be added to the spec to address this issue.
