### ISSUE TITLE
Notify callbacks when monitoring list of remote playback devices is stopped

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#84]
From https://github.com/w3c/remote-playback/pull/83#discussion_r115578646

@avayvod proposes to fire availability callbacks with `false` before clearing the global set of callbacks, so that pages do not continue to believe that there are available playback devices.

**Comment by avayvod** [comment]
Hm, I don't propose clearing the set though - it might also break sites when they try to cancelWatchAvailability with the callback ids they saved and it suddenly throws an exception.

@beaufortfrancois FYI

**Comment by markafoltz** [comment]
So "stopping" is more like "pausing" is what you are saying.  Presumably there would also be steps to "resume?"

**Comment by avayvod** [comment]
So, I think two cases - one when the page adds disableRemotePlayback attribute to a media element. The page then can expect the callbacks not being fired and the availability be ignored. One may argue that the callbacks could be set by a media player library and the attribute set by the hosting page, but the attribute mutation can be observed via MutationObserver and so on. I don't think the spec needs to change for this case.

Now the second case brought up in the PR #83 is when the user disables availability monitoring or even remote playback, for example, using the web browser settings. This is an external event to the page so I think the user agent needs to behave in a non breaking way, consistently with the API. Which means not clearing the callbacks and report availability as false. "Resume" in this context happens when the user changes the setting back. In this case, the existing callbacks should get called with availability true as if nothing happened. Otherwise, user would have to refresh the page after changing the settings.

I don't think such user agent specific, page agnostic behavior needs to be in the spec in anything more than a note.

**Comment by markafoltz** [comment]
Fair enough.  User agent level controls generally aren't described with specific algorithms in specs as far as I've seen.

So the conclusions you propose are that 

1. "disabling remote playback" via user agent controls is not related to the disableRemotePlayback attribute or its implementation.

2. A note should be added suggesting user agents manage callbacks as you suggest when the user disables or enables monitoring and remote playback via user agent controls.

**Comment by avayvod** [comment]
Yes. That's a good summary!

**Comment by markafoltz** [comment]
Closing as I believe this is addressed by the PR.
